version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=message_api_db
    expose:
      - 5432
  web:
    build: .
    command: uvicorn main:app  --reload --host 0.0.0.0
    volumes:
      - .:/usr/src/api_backend
    ports:
      - 8000:8000